### ISSUE TITLE
Processing v4 support

### ISSUE THREAD

**Issue by codingjoe** [pr1metine/setup-processing#6]
Hi there,

I just tried upgrading a project to v4. It seems they no longer upload releases to their download server, but use GitHub releases instead. Any chance we get support for this version soon? I'd be happy to help.

Cheers!
Joe

**Comment by pr1metine** [comment]
Hi Joe,
I'm super sorry. Don't know how I missed your issue. I pushed a new release, hope it is to your liking.

Yours,
Thanh

**Comment by codingjoe** [comment]
FYI, the folder in which the processing gets dumped is no longer the "version" or tag. For the 4.2 tag is `1292.0.0`.

**Comment by pr1metine** [comment]
Yeah. Should I expose the install dir as a variable?

**Comment by codingjoe** [comment]
> Yeah. Should I expose the install dir as a variable?

Yes, that'd be cool!

**Comment by pr1metine** [comment]
Ok, implemented with v2.1.0. Please reach out if there's something else I can do for you

**Comment by codingjoe** [comment]
@pr1metine thanks for the quick turn around on that. I am experiencing some issues tho: https://github.com/codingjoe/MusicBeam/pull/99
